footer: mob, tab, desktop
perpera/plan_b_project pull request #8
Opened 2023-07-02 17:33 UTC by NadiiaChernokur

2023-07-02 20:53 UTC, perpera requested changes
Чудова робота! (:
Але замініть, будь-ласка, колір фону на змінну. Зверніть увагу, що логотип має інакший відтінок зеленого, у списку змінних - --logo-color. Також логотип має бути посиланням (на початок основної сторінки). А посилання на соц-мережі мають перекидати на нове вікно в браузері.
Чекаю на новий коміт!

2023-07-03 08:16 UTC, perpera requested changes
https://www.loom.com/share/66318593256440d085156f617b991c1b?sid=0d803206-c81e-461c-ac3f-6880920626b0
Посилання на коментарі(:

2023-07-03 11:19 UTC, perpera requested changes
Ще тільки транзішн треба додати до якірних посилань🙏🏻

2023-07-03 16:56 UTC, NadiiaChernokur commented
Вибачте , щось я дуже неуважна...

2023-07-03 19:58 UTC, perpera approved these changes
Все чудово!❤️

2023-07-03 19:59 UTC, merged